# fly.toml app configuration file generated for highstrangenessbot on 2023-09-24T23:42:33Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "highstrangenessbot"
primary_region = "dfw"
kill_signal = "SIGINT"
kill_timeout = "5s"

[build]
